### ISSUE TITLE
Clearing up some concepts

### ISSUE THREAD

**Issue by prateekm08** [aamir-mustafa/pcl-adversarial-defense#11]
Could you please enlighten us as to the meaning of ```Proximity``` and ```Con_Proximity``` in the codebase? The paper does not mention these.

**Comment by aamir-mustafa** [comment]
Hey,
Proximity refers to the first term in Eq 5 of the paper and Con_Proximity refers to the second term in the equation.

Hope that helps

**Comment by rowedenny** [comment]
Sorry to bother, but referring to the code, I am more confused.
1. The second term in eq5 has two terms: the average distance between x and non-label centers, and the average distance between all non-label center pairs. Yet in Con_Proximity, the distance between non-label pairs seem not account. 
2. Based on my understanding, the centers are expected to be shared between `Proximity` and `Con_Proximity`, however, the attribute `centers` are individual independent for both class,  it seems that the center in `Proximity` and `Con_Proximity` are not shared.

Would you mind pointing out any flaw on my interpretation, and share your thoughts about it?
