### ISSUE TITLE
black box attack

### ISSUE THREAD

**Issue by kk1153** [aamir-mustafa/pcl-adversarial-defense#2]
can you tell which scripts to use for black box attack?

**Comment by aamir-mustafa** [comment]
We have not uploaded the scripts for running black box attacks. For that we need to provide the scripts from other papers we well, which we are not entitled to do.
To check the basic robustness against black box settings, you can use our codes to generate adversarial images (another repository) for another model and test those attacked images on our model.
Hope this helps

**Comment by kk1153** [comment]
Thanks, can you refer me here to the link of repositories which you have used for this black box attacks in the paper.

**Comment by aamir-mustafa** [comment]
The repository is not for implementing black box attacks for this paper. It is a general repository to generate adversarial images. It might help you. Following is the link:
https://github.com/aamir-mustafa/generate-adv-examples

**Comment by kartikgupta-at-anu** [comment]
Thanks @aamir

**Comment by kk1153** [comment]
Thanks @aamir-mustafa
