### ISSUE TITLE
CIFAR10_PCL_AdvTrain_PGD.pth.tar and CIFAR10_PCL_AdvTrain_FGSM.pth.tar ?

### ISSUE THREAD

**Issue by AliShahin** [aamir-mustafa/pcl-adversarial-defense#5]
Hi,

Could you please provide CIFAR10_PCL_AdvTrain_PGD.pth.tar and CIFAR10_PCL_AdvTrain_FGSM.pth.tar? 
And could you clarify what is robust_model.pth.tar for?

**Comment by aamir-mustafa** [comment]
Hi, 
We have provided the best performing model named: robust_model.pth.tar

Thanks

**Comment by Harry-Up** [comment]
@aamir-mustafa Thanks for your work and sharing! I am trying to test the acc and adv_acc of the model with the provided files robust_model.pth.tar. However, the adv_acc of robust_model is not supposed, which is 37.28% compared to 58.5% in the paper. My system is Ubuntu 18.04, python 3.7, PyTorch 1.5.0, and  CUDA 10.2. Any suggestion?

![image](https://user-images.githubusercontent.com/26539945/86524610-2951c380-beaf-11ea-9699-849431fd5b0c.png)

![image](https://user-images.githubusercontent.com/26539945/86524612-2f47a480-beaf-11ea-8407-c558e0a9b0a7.png)

Now I am trying to re-train the model with pcl_training_adversarial_pgd.py.
