### ISSUE TITLE
Proxity and Conproxity losses share different prototype centers in code

### ISSUE THREAD

**Issue by krishnakanthnakka** [aamir-mustafa/pcl-adversarial-defense#9]
As per Eq 5 of the paper, the prototypes centers for proximity loss and con-proximity loss should be the same. However, from the code, we can see different sets of prototypes for both losses. Can you please share your thoughts.

Please correct me I'm wrong.

**Comment by aamir-mustafa** [comment]
Hi,

Since the optimization step is made after computing the centres for both proximity and con_proximity losses, we have asssumed in our implementation that the centres chosen whould be closer (if not exact) in each case.

Hope that helps.
